COMPTE_COURANT = '1'
COMPTE_EPARGNE = '2'

APP_SOLDE = '1'
APP_RETRAIT = '2'
APP_VERSEMENT = '3'
APP_QUITTER = '4'

TEST_TYPE = ['1', '2']
TEST_DEPOSIT = ['1', '2']
TEST_OPERATION = ['1', '2', '3', '4']
